### PR TITLE
added iter method to go over chunks of data

### PR DESCRIPTION
**Pull request by wabu**
```
with (yield from cli.cursor()) as cur:
    yield from cur.execute("SELECT * FROM table")
    for fetch_chunk in cur.iter():
        rows = yield from fetch_chunk
        print('fetched %d rows ...' % len(rows)
```

### CODE REVIEW

**Comment by tailhook** [comment]
Hi. This is a nice work. I'm not sure why `__getattr__` hack is needed.

Anyway, I'm not going to support this project any more. I may just transfer ownership to you, if you like.

**Comment by wabu** [comment]
ok. Currently we consider using it as our default interface to hive.
Is your thrift asyncio branch is still active?

**Comment by tailhook** [comment]
> Is your thrift asyncio branch is still active? 

I'm not sure. The only use of it was in aio-hs2. But in hadoop infrastructure there are other services that use thrift, so I may use it in future. aio-thrift has few problems, which I haven't fixed (e.g. timeouts), and I'm not going to fix them soom. So I'd consider it unmaintained too.

Ideally thrift asyncio branch should be included into thrift mainline. But even python3 is not supported in thrift mainline yet, so it's not going to be done soon.

Anyway, let me know if you are going to maintain thrift/python3/asyncio.

**Comment by tailhook** [comment]
Now, it's a good time to close the PR :) Thanks for your contribution anyway.

**Pull request closed without merging**
